### ISSUE TITLE
Construct FC-ResNets Using fcn_maker Sample

### ISSUE THREAD

**Issue by ferasodh** [veugene/fcn_maker#6]
Hi,

Is it possible to construct a [FC-ResNets](https://arxiv.org/pdf/1702.05174.pdf) network using fcn_maker? Could you please give a sample how this can be done?

Thanks,

**Comment by veugene** [comment]
The model in the normalized inputs paper is made by stacking a ResUNet on the output of a UNet. The UNet, which acts as the preprocessing network, does not use batch norm and outputs a single feature map rather than a probability map.

As in the examples, you can make a unet with `assemble_unet`. Use `num_classes=None` to avoid producing a probability map output. Set layer parameters as described in table 1 of the paper.

For some input_shape, table1_kwargs:

```python
from keras.models import Model
from keras.layers import Input
from fcn_maker.blocks import (Convolution,
                              basic_block_mp,
                              bottleneck,
                              get_channel_axis)
from fcn_maker.model import (assemble_unet,
                             assemble_resunet)

# define input_shape
# define table1_kwargs - from table 1 in paper

input = Input(input_shape)

model1 = assemble_unet(input_shape=input_shape,
                       num_classes=None,
                       **table1_kwargs)

model2 = assemble_resunet(input_shape=input_shape,
                          num_classes=1,
                          num_init_blocks=1,
                          num_main_blocks=3,
                          main_block_depth=[3, 8, 10, 3, 10, 8, 3],
                          init_num_filters=32)

out = model1(input)
out = Convolution(filters=input_shape[get_channel_axis()],
                  kernel_size=3,
                  padding='same')(out)
out = model2(out)

FC_ResNet = Model(inputs=input, ouputs=out)
```

Please note that "simple block" is `basic_block_mp` (or `tiny_block` in the pytorch code). The above should implement the model in keras; there's also a pytorch branch I'm working on.

**Comment by ferasodh** [comment]
Thank you so much

**Comment by ferasodh** [comment]
I got this error ValueError: The channel dimension of the inputs should be defined. Found `None`.  Is there something wrong with model kwargs?

def get_fc_resnet():
    # define input_shape
    model_kwargs = OrderedDict((
    ('short_skip', True),
    ('long_skip', True),
    ('long_skip_merge_mode', 'sum'),
    ('upsample_mode', 'repeat'),
    ('dropout', 0.1),
    ('weight_decay', 0.0001), 
    ('init', 'he_normal'),
    ('nonlinearity', 'relu'),
    ('ndim', 2),
    ('verbose', True)                           # Set False to silence stdout
    ))
    input_shape = (256, 256, 3)
    input = Input(input_shape)

    model1 = assemble_unet(input_shape=input_shape,
                           num_classes=None,
                           **model_kwargs)

    model2 = assemble_resunet(input_shape=(1, None, None),
                              num_classes=1,
                              num_init_blocks=1,
                              num_main_blocks=3,
                              main_block_depth=[3, 8, 10, 3, 10, 8, 3],
                              init_num_filters=32)

    out = model1(input)
    out = Convolution(filters=1, kernel_size=3, padding='same')(out)
    out = model2(out)

    return Model(inputs=input, ouputs=out)

Thanks,

**Comment by veugene** [comment]
Mind the input shapes.

Looking at your channel axis, it seems that you're using tf. Try using the code in the first comment -- a couple minutes after I wrote it, I edited it to be more generic. It assumed a 1-channel input with the theano backend. The point of that conv is to make the output of the unet have the same number of channels as the input.

**Comment by ferasodh** [comment]
Thanks it was a problem with the input shapes as you mentioned
